version: '3.8'

services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: syntropy-db
    environment:
      POSTGRES_USER: syntropy
      POSTGRES_PASSWORD: syntropy_dev_password
      POSTGRES_DB: syntropy_calculator
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U syntropy"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
