[build]
  command = "cd app && npm install && npm run build"
  publish = "app/build"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "app/.netlify/functions"
